export const LISTE_BATTERIES = {
  liste_techno: [
    "plomb_acide_flooded",
    "agm_gel",
    "lifepo4",
    "lithium_nmc_nca",
    "nicd",
  ],
  catalogue_batt: {
    plomb_acide_flooded: {
      label: "Plomb-acide (Ouverte/Flooded)",
      options: [
        { nom: "1", v: 6, ah: 180, desc: "Traction légère / Voiturette" },
        {
          nom: "2",
          v: 6,
          ah: 225,
          desc: "Solaire cycle profond (T-105 style)",
        },
        { nom: "3", v: 12, ah: 35, desc: "Petite cylindrée / Groupe secours" },
        { nom: "4", v: 12, ah: 45, desc: "Citadine standard" },
        { nom: "5", v: 12, ah: 60, desc: "Berline / Usage domestique léger" },
        { nom: "6", v: 12, ah: 75, desc: "Utilitaire / Installation 12V" },
        { nom: "7", v: 12, ah: 90, desc: "Camionnette / Backup" },
        { nom: "8", v: 12, ah: 100, desc: "Solaire classique" },
        { nom: "9", v: 12, ah: 110, desc: "Loisirs / Marine" },
        { nom: "10", v: 12, ah: 125, desc: "Stockage moyen" },
        {
          nom: "11",
          v: 12,
          ah: 150,
          desc: "Standard Solaire RDC (Grand public)",
        },
        { nom: "12", v: 12, ah: 180, desc: "Gros utilitaire / Stationnaire" },
        { nom: "13", v: 12, ah: 200, desc: "Standard Solaire RDC (Premium)" },
        { nom: "14", v: 12, ah: 220, desc: "Gros onduleur" },
        { nom: "15", v: 12, ah: 250, desc: "Capacité maximale monobloc 12V" },
        { nom: "16", v: 2, ah: 200, desc: "Cellule OPzS (Unité)" },
        { nom: "17", v: 2, ah: 600, desc: "Cellule OPzS industrielle" },
        { nom: "18", v: 2, ah: 1500, desc: "Stationnaire Très Haute Capacité" },
      ],
    },

    agm_gel: {
      label: "AGM / Gel (VRLA)",
      options: [
        { nom: "19", v: 12, ah: 1.2, desc: "Alarme incendie / Secours" },
        { nom: "20", v: 12, ah: 4.5, desc: "Jouets / Équipement médical" },
        { nom: "21", v: 12, ah: 7.2, desc: "Standard UPS (Onduleur bureau)" },
        { nom: "22", v: 12, ah: 9, desc: "UPS Haute performance" },
        { nom: "23", v: 12, ah: 12, desc: "Petit scooter / Alarme" },
        { nom: "24", v: 12, ah: 18, desc: "Onduleur serveur léger" },
        { nom: "25", v: 12, ah: 26, desc: "Télécom / Backup local" },
        { nom: "26", v: 12, ah: 33, desc: "Fauteuil roulant électrique" },
        { nom: "27", v: 12, ah: 40, desc: "AGM démarrage Stop&Start" },
        { nom: "28", v: 12, ah: 55, desc: "Mobilité / Énergie" },
        { nom: "29", v: 12, ah: 65, desc: "Solaire Deep Cycle" },
        { nom: "30", v: 12, ah: 80, desc: "Gel Marine / Camping-car" },
        { nom: "31", v: 12, ah: 100, desc: "Solaire Premium (DOD 50%)" },
        { nom: "32", v: 12, ah: 120, desc: "Onduleur hybride" },
        { nom: "33", v: 12, ah: 150, desc: "Stockage Gel haute capacité" },
        { nom: "34", v: 12, ah: 200, desc: "Standard Gel (Solaire/Backup)" },
        { nom: "35", v: 12, ah: 230, desc: "Gros stockage étanche" },
        { nom: "36", v: 2, ah: 1000, desc: "Cellule OPzV industrielle" },
        { nom: "37", v: 2, ah: 2000, desc: "Stationnaire Télécom / Réseau" },
      ],
    },

    lifepo4: {
      label: "Lithium Fer Phosphate (LFP)",
      options: [
        { nom: "38", v: 3.2, ah: 100, desc: "Cellule prismatique DIY" },
        { nom: "39", v: 3.2, ah: 280, desc: "Cellule DIY Standard (EVE/CATL)" },
        { nom: "40", v: 12.8, ah: 12, desc: "Remplace Plomb 12Ah" },
        { nom: "41", v: 12.8, ah: 50, desc: "Camping / Portable" },
        { nom: "42", v: 12.8, ah: 100, desc: "Remplace Plomb 100Ah (Drop-in)" },
        { nom: "43", v: 12.8, ah: 200, desc: "Unité 12V 2.5kWh" },
        { nom: "44", v: 12.8, ah: 300, desc: "Forte autonomie 12V" },
        { nom: "45", v: 25.6, ah: 50, desc: "Solaire 24V compact" },
        { nom: "46", v: 25.6, ah: 100, desc: "Solaire 24V standard (2.5kWh)" },
        {
          nom: "47",
          v: 25.6,
          ah: 200,
          desc: "Solaire 24V haute capacité (5kWh)",
        },
        { nom: "48", v: 51.2, ah: 50, desc: "Rack Télécom 48V léger" },
        { nom: "49", v: 51.2, ah: 100, desc: "Standard Rack 48V (5.12kWh)" },
        {
          nom: "50",
          v: 51.2,
          ah: 105,
          desc: "Modèle vertical (Powerwall style)",
        },
        { nom: "51", v: 51.2, ah: 150, desc: "Stockage intermédiaire" },
        { nom: "52", v: 51.2, ah: 200, desc: "Rack Haute Capacité (10kWh)" },
        { nom: "53", v: 51.2, ah: 280, desc: "Pack Haute densité (14kWh)" },
        { nom: "54", v: 96, ah: 100, desc: "Haute Tension (HV) résidentielle" },
        { nom: "55", v: 192, ah: 50, desc: "Système HV Industriel" },
        { nom: "56", v: 384, ah: 100, desc: "Stockage Tertiaire / Micro-grid" },
      ],
    },

    lithium_nmc_nca: {
      label: "Lithium NMC / NCA",
      options: [
        { nom: "57", v: 3.7, ah: 2.6, desc: "Cellule 18650 standard" },
        { nom: "58", v: 3.7, ah: 3.5, desc: "Cellule 18650 haute capacité" },
        { nom: "59", v: 3.7, ah: 5.0, desc: "Cellule 21700 (Tesla/Panasonic)" },
        { nom: "60", v: 7.4, ah: 2.2, desc: "Appareils photo / Électronique" },
        { nom: "61", v: 11.1, ah: 5.0, desc: "Lipo Drone / Modélisme" },
        { nom: "62", v: 14.8, ah: 10, desc: "Équipement médical / Vidéo" },
        { nom: "63", v: 24, ah: 20, desc: "Robotique / Outillage" },
        { nom: "64", v: 36, ah: 10, desc: "Vélos électriques (E-bike)" },
        { nom: "65", v: 36, ah: 17.5, desc: "E-bike longue distance" },
        { nom: "66", v: 48, ah: 13, desc: "Trottinette électrique" },
        { nom: "67", v: 48, ah: 20, desc: "Trottinette haute performance" },
        { nom: "68", v: 48, ah: 100, desc: "Backup haute densité compact" },
        { nom: "69", v: 60, ah: 30, desc: "Scooter électrique" },
        { nom: "70", v: 72, ah: 45, desc: "Moto électrique" },
        { nom: "71", v: 72, ah: 60, desc: "Moto électrique (Long Range)" },
        { nom: "72", v: 96, ah: 120, desc: "Véhicule utilitaire léger" },
        { nom: "73", v: 350, ah: 150, desc: "Batterie EV (Berline)" },
        { nom: "74", v: 400, ah: 230, desc: "Batterie EV (SUV/Haut de gamme)" },
      ],
    },

    nicd: {
      label: "Nickel-Cadmium",
      options: [
        { nom: "75", v: 1.2, ah: 1.2, desc: "Format AA industriel" },
        { nom: "76", v: 1.2, ah: 4.5, desc: "Format D industriel" },
        { nom: "77", v: 1.2, ah: 20, desc: "Cellule KH (Stationnaire)" },
        { nom: "78", v: 1.2, ah: 50, desc: "Cellule KPL (Basse décharge)" },
        { nom: "79", v: 1.2, ah: 80, desc: "Cellule KPM (Moyenne décharge)" },
        { nom: "80", v: 1.2, ah: 100, desc: "Cellule KPH (Haute décharge)" },
        { nom: "81", v: 1.2, ah: 250, desc: "Usage ferroviaire" },
        { nom: "82", v: 1.2, ah: 500, desc: "Gros stockage industriel" },
        { nom: "83", v: 1.2, ah: 1200, desc: "Capacité géante (Centrale)" },
        { nom: "84", v: 12, ah: 40, desc: "Bloc démarrage turbine" },
        { nom: "85", v: 12, ah: 100, desc: "Bloc secours hôpital" },
        { nom: "86", v: 24, ah: 50, desc: "Système embarqué marine" },
        { nom: "87", v: 24, ah: 120, desc: "Backup Pétrolier / Gazier" },
        { nom: "88", v: 48, ah: 100, desc: "Télécoms désertiques" },
        { nom: "89", v: 48, ah: 200, desc: "Backup réseau critique" },
        { nom: "90", v: 96, ah: 60, desc: "Ascenseurs / Sécurité" },
        { nom: "91", v: 110, ah: 150, desc: "Sous-station électrique" },
        { nom: "92", v: 120, ah: 200, desc: "Contrôle-commande ferroviaire" },
      ],
    },
  },
};
