export const LISTE_BATTERIES = {
  liste_techno: ["plomb_acide_flooded","agm_gel","lifepo4","lithium_nmc_nca","nicd",],
  catalogue_batt: {
    plomb_acide_flooded: {
      label: "Plomb-acide (Ouverte/Flooded)",
      options: [
        { nom: "", v: 6, ah: 180, desc: "Traction légère / Voiturette" },
        { nom: "", v: 6, ah: 225, desc: "Solaire cycle profond (T-105 style)" },
        { nom: "", v: 12, ah: 35, desc: "Petite cylindrée / Groupe secours" },
        { nom: "", v: 12, ah: 45, desc: "Citadine standard" },
        { nom: "", v: 12, ah: 60, desc: "Berline / Usage domestique léger" },
        { nom: "", v: 12, ah: 75, desc: "Utilitaire / Installation 12V" },
        { nom: "", v: 12, ah: 90, desc: "Camionnette / Backup" },
        { nom: "", v: 12, ah: 100, desc: "Solaire classique" },
        { nom: "", v: 12, ah: 110, desc: "Loisirs / Marine" },
        { nom: "", v: 12, ah: 125, desc: "Stockage moyen" },
        {
          nom: "",
          v: 12,
          ah: 150,
          desc: "Standard Solaire RDC (Grand public)",
        },
        { nom: "", v: 12, ah: 180, desc: "Gros utilitaire / Stationnaire" },
        { nom: "", v: 12, ah: 200, desc: "Standard Solaire RDC (Premium)" },
        { nom: "", v: 12, ah: 220, desc: "Gros onduleur" },
        { nom: "", v: 12, ah: 250, desc: "Capacité maximale monobloc 12V" },
        { nom: "", v: 2, ah: 200, desc: "Cellule OPzS (Unité)" },
        { nom: "", v: 2, ah: 600, desc: "Cellule OPzS industrielle" },
        { nom: "", v: 2, ah: 1500, desc: "Stationnaire Très Haute Capacité" },
      ],
    },

    agm_gel: {
      label: "AGM / Gel (VRLA)",
      options: [
        { nom: "", v: 12, ah: 1.2, desc: "Alarme incendie / Secours" },
        { nom: "", v: 12, ah: 4.5, desc: "Jouets / Équipement médical" },
        { nom: "", v: 12, ah: 7.2, desc: "Standard UPS (Onduleur bureau)" },
        { nom: "", v: 12, ah: 9, desc: "UPS Haute performance" },
        { nom: "", v: 12, ah: 12, desc: "Petit scooter / Alarme" },
        { nom: "", v: 12, ah: 18, desc: "Onduleur serveur léger" },
        { nom: "", v: 12, ah: 26, desc: "Télécom / Backup local" },
        { nom: "", v: 12, ah: 33, desc: "Fauteuil roulant électrique" },
        { nom: "", v: 12, ah: 40, desc: "AGM démarrage Stop&Start" },
        { nom: "", v: 12, ah: 55, desc: "Mobilité / Énergie" },
        { nom: "", v: 12, ah: 65, desc: "Solaire Deep Cycle" },
        { nom: "", v: 12, ah: 80, desc: "Gel Marine / Camping-car" },
        { nom: "", v: 12, ah: 100, desc: "Solaire Premium (DOD 50%)" },
        { nom: "", v: 12, ah: 120, desc: "Onduleur hybride" },
        { nom: "", v: 12, ah: 150, desc: "Stockage Gel haute capacité" },
        { nom: "", v: 12, ah: 200, desc: "Standard Gel (Solaire/Backup)" },
        { nom: "", v: 12, ah: 230, desc: "Gros stockage étanche" },
        { nom: "", v: 2, ah: 1000, desc: "Cellule OPzV industrielle" },
        { nom: "", v: 2, ah: 2000, desc: "Stationnaire Télécom / Réseau" },
      ],
    },

    lifepo4: {
      label: "Lithium Fer Phosphate (LFP)",
      options: [
        { nom: "", v: 3.2, ah: 100, desc: "Cellule prismatique DIY" },
        { nom: "", v: 3.2, ah: 280, desc: "Cellule DIY Standard (EVE/CATL)" },
        { nom: "", v: 12.8, ah: 12, desc: "Remplace Plomb 12Ah" },
        { nom: "", v: 12.8, ah: 50, desc: "Camping / Portable" },
        { nom: "", v: 12.8, ah: 100, desc: "Remplace Plomb 100Ah (Drop-in)" },
        { nom: "", v: 12.8, ah: 200, desc: "Unité 12V 2.5kWh" },
        { nom: "", v: 12.8, ah: 300, desc: "Forte autonomie 12V" },
        { nom: "", v: 25.6, ah: 50, desc: "Solaire 24V compact" },
        { nom: "", v: 25.6, ah: 100, desc: "Solaire 24V standard (2.5kWh)" },
        {
          nom: "",
          v: 25.6,
          ah: 200,
          desc: "Solaire 24V haute capacité (5kWh)",
        },
        { nom: "", v: 51.2, ah: 50, desc: "Rack Télécom 48V léger" },
        { nom: "", v: 51.2, ah: 100, desc: "Standard Rack 48V (5.12kWh)" },
        {
          nom: "",
          v: 51.2,
          ah: 105,
          desc: "Modèle vertical (Powerwall style)",
        },
        { nom: "", v: 51.2, ah: 150, desc: "Stockage intermédiaire" },
        { nom: "", v: 51.2, ah: 200, desc: "Rack Haute Capacité (10kWh)" },
        { nom: "", v: 51.2, ah: 280, desc: "Pack Haute densité (14kWh)" },
        { nom: "", v: 96, ah: 100, desc: "Haute Tension (HV) résidentielle" },
        { nom: "", v: 192, ah: 50, desc: "Système HV Industriel" },
        { nom: "", v: 384, ah: 100, desc: "Stockage Tertiaire / Micro-grid" },
      ],
    },

    lithium_nmc_nca: {
      label: "Lithium NMC / NCA",
      options: [
        { nom: "", v: 3.7, ah: 2.6, desc: "Cellule 18650 standard" },
        { nom: "", v: 3.7, ah: 3.5, desc: "Cellule 18650 haute capacité" },
        { nom: "", v: 3.7, ah: 5.0, desc: "Cellule 21700 (Tesla/Panasonic)" },
        { nom: "", v: 7.4, ah: 2.2, desc: "Appareils photo / Électronique" },
        { nom: "", v: 11.1, ah: 5.0, desc: "Lipo Drone / Modélisme" },
        { nom: "", v: 14.8, ah: 10, desc: "Équipement médical / Vidéo" },
        { nom: "", v: 24, ah: 20, desc: "Robotique / Outillage" },
        { nom: "", v: 36, ah: 10, desc: "Vélos électriques (E-bike)" },
        { nom: "", v: 36, ah: 17.5, desc: "E-bike longue distance" },
        { nom: "", v: 48, ah: 13, desc: "Trottinette électrique" },
        { nom: "", v: 48, ah: 20, desc: "Trottinette haute performance" },
        { nom: "", v: 48, ah: 100, desc: "Backup haute densité compact" },
        { nom: "", v: 60, ah: 30, desc: "Scooter électrique" },
        { nom: "", v: 72, ah: 45, desc: "Moto électrique" },
        { nom: "", v: 72, ah: 60, desc: "Moto électrique (Long Range)" },
        { nom: "", v: 96, ah: 120, desc: "Véhicule utilitaire léger" },
        { nom: "", v: 350, ah: 150, desc: "Batterie EV (Berline)" },
        { nom: "", v: 400, ah: 230, desc: "Batterie EV (SUV/Haut de gamme)" },
      ],
    },

    nicd: {
      label: "Nickel-Cadmium",
      options: [
        { nom: "", v: 1.2, ah: 1.2, desc: "Format AA industriel" },
        { nom: "", v: 1.2, ah: 4.5, desc: "Format D industriel" },
        { nom: "", v: 1.2, ah: 20, desc: "Cellule KH (Stationnaire)" },
        { nom: "", v: 1.2, ah: 50, desc: "Cellule KPL (Basse décharge)" },
        { nom: "", v: 1.2, ah: 80, desc: "Cellule KPM (Moyenne décharge)" },
        { nom: "", v: 1.2, ah: 100, desc: "Cellule KPH (Haute décharge)" },
        { nom: "", v: 1.2, ah: 250, desc: "Usage ferroviaire" },
        { nom: "", v: 1.2, ah: 500, desc: "Gros stockage industriel" },
        { nom: "", v: 1.2, ah: 1200, desc: "Capacité géante (Centrale)" },
        { nom: "", v: 12, ah: 40, desc: "Bloc démarrage turbine" },
        { nom: "", v: 12, ah: 100, desc: "Bloc secours hôpital" },
        { nom: "", v: 24, ah: 50, desc: "Système embarqué marine" },
        { nom: "", v: 24, ah: 120, desc: "Backup Pétrolier / Gazier" },
        { nom: "", v: 48, ah: 100, desc: "Télécoms désertiques" },
        { nom: "", v: 48, ah: 200, desc: "Backup réseau critique" },
        { nom: "", v: 96, ah: 60, desc: "Ascenseurs / Sécurité" },
        { nom: "", v: 110, ah: 150, desc: "Sous-station électrique" },
        { nom: "", v: 120, ah: 200, desc: "Contrôle-commande ferroviaire" },
      ],
    },
  },
};
