export const LISTE_PANNEAUX = {
  liste_marques: [
    "jinko_solar",
    "trina_solar",
    "longi_solar",
    "canadian_solar",
    "ja_solar",
    "tongwei_solar",
    "astronergy",
    "risen_energy",
    "aiko_solar",
    "dmegc_solar",
    "qcells",
    "maxeon",
    "huasun",
    "gcl_system",
    "recom",
    "talesun",
    "znshine_solar",
    "haitai_solar",
    "victron_energy",
    "ae_solar",
    "meyer_burger",
    "rec_solar",
    "suntech",
    "yingli_solar",
    "phono_solar",
    "seraphim",
    "dah_solar",
    "luxen_solar",
    "sharp",
    "vikram_solar",
    "sunnypower",
    "voltec_solar",
    "dualsun",
    "futurasun",
    "axitec",
  ],
  catalogue_pv: {
    jinko_solar: {
      nom_afic: "Jinko Solar",
      modeles: [
        {
          nom: "Tiger Neo 3.0 670W",
          puissance_max: 670,
          tension_mpp: 46.22,
          tension_vide: 55.84,
          courant_mpp: 14.5,
          courant_cc: 15.22,
          coeff_v: -0.25,
          coeff_p: -0.29,
          coeff_i: 0.045,
          noct: 45,
          longueur_mm: 2382,
          largeur_mm: 1134,
          epaisseur_mm: 30,
          surface_m2: 2.7,
          poids_kg: 32.5,
          nb_cellules: 264,
          format_cellules: "182x210mm",
          type: "bifacial_double_glass",
        },
        {
          nom: "Tiger Neo 620W",
          puissance_max: 620,
          tension_mpp: 45.46,
          tension_vide: 55.44,
          courant_mpp: 13.64,
          courant_cc: 14.43,
          coeff_v: -0.25,
          coeff_p: -0.29,
          coeff_i: 0.045,
          noct: 45,
          longueur_mm: 2382,
          largeur_mm: 1134,
          epaisseur_mm: 30,
          surface_m2: 2.7,
          poids_kg: 32.5,
          nb_cellules: 264,
          format_cellules: "182x210mm",
          type: "bifacial_double_glass",
        },
        {
          nom: "Tiger Neo 575W",
          puissance_max: 575,
          tension_mpp: 42.22,
          tension_vide: 50.88,
          courant_mpp: 13.62,
          courant_cc: 14.39,
          coeff_v: -0.25,
          coeff_p: -0.29,
          coeff_i: 0.045,
          noct: 45,
          longueur_mm: 2278,
          largeur_mm: 1134,
          epaisseur_mm: 30,
          surface_m2: 2.58,
          poids_kg: 28.5,
          nb_cellules: 144,
          format_cellules: "182x182mm",
          type: "bifacial_double_glass",
        },
        {
          nom: "Tiger Pro 545W",
          puissance_max: 545,
          tension_mpp: 40.8,
          tension_vide: 49.52,
          courant_mpp: 13.36,
          courant_cc: 13.94,
          coeff_v: -0.28,
          coeff_p: -0.35,
          coeff_i: 0.048,
          noct: 45,
          longueur_mm: 2278,
          largeur_mm: 1134,
          epaisseur_mm: 35,
          surface_m2: 2.58,
          poids_kg: 28.0,
          nb_cellules: 144,
          format_cellules: "182x182mm",
          type: "monofacial",
        },
        {
          nom: "Tiger 400W All-Black",
          puissance_max: 400,
          tension_mpp: 30.42,
          tension_vide: 37.01,
          courant_mpp: 13.15,
          courant_cc: 13.93,
          coeff_v: -0.28,
          coeff_p: -0.35,
          coeff_i: 0.048,
          noct: 45,
          longueur_mm: 1722,
          largeur_mm: 1134,
          epaisseur_mm: 30,
          surface_m2: 1.95,
          poids_kg: 21.5,
          nb_cellules: 108,
          format_cellules: "182x182mm",
          type: "monofacial_all_black",
        },
      ],
    },
    trina_solar: {
      nom_afic: "Trina Solar",
      modeles: [
        {
          nom: "Vertex 670W",
          puissance_max: 670,
          tension_mpp: 38.2,
          tension_vide: 46.1,
          courant_mpp: 17.55,
          courant_cc: 18.62,
          coeff_v: -0.24,
          coeff_p: -0.3,
          coeff_i: 0.04,
          noct: 43,
          longueur_mm: 2384,
          largeur_mm: 1303,
          epaisseur_mm: 35,
          surface_m2: 3.11,
          poids_kg: 33.6,
          nb_cellules: 132,
          format_cellules: "210x210mm",
          type: "monofacial",
        },
        {
          nom: "Vertex N 610W",
          puissance_max: 610,
          tension_mpp: 45.3,
          tension_vide: 54.8,
          courant_mpp: 13.47,
          courant_cc: 14.28,
          coeff_v: -0.24,
          coeff_p: -0.29,
          coeff_i: 0.04,
          noct: 43,
          longueur_mm: 2382,
          largeur_mm: 1134,
          epaisseur_mm: 30,
          surface_m2: 2.7,
          poids_kg: 32.0,
          nb_cellules: 144,
          format_cellules: "182x210mm",
          type: "bifacial_double_glass",
        },
        {
          nom: "Vertex 550W",
          puissance_max: 550,
          tension_mpp: 31.6,
          tension_vide: 37.9,
          courant_mpp: 17.4,
          courant_cc: 18.52,
          coeff_v: -0.25,
          coeff_p: -0.34,
          coeff_i: 0.04,
          noct: 43,
          longueur_mm: 2384,
          largeur_mm: 1303,
          epaisseur_mm: 35,
          surface_m2: 3.11,
          poids_kg: 33.3,
          nb_cellules: 132,
          format_cellules: "210x210mm",
          type: "monofacial",
        },
        {
          nom: "Vertex S+ 445W",
          puissance_max: 445,
          tension_mpp: 44.3,
          tension_vide: 52.6,
          courant_mpp: 10.05,
          courant_cc: 10.71,
          coeff_v: -0.24,
          coeff_p: -0.3,
          coeff_i: 0.04,
          noct: 43,
          longueur_mm: 1762,
          largeur_mm: 1134,
          epaisseur_mm: 30,
          surface_m2: 2.0,
          poids_kg: 23.0,
          nb_cellules: 120,
          format_cellules: "182x182mm",
          type: "bifacial_double_glass",
        },
      ],
    },
    longi_solar: {
      nom_afic: "LONGi Solar",
      modeles: [
        {
          nom: "Hi-MO 7 600W",
          puissance_max: 600,
          tension_mpp: 44.86,
          tension_vide: 53.15,
          courant_mpp: 13.38,
          courant_cc: 14.28,
          coeff_v: -0.23,
          coeff_p: -0.28,
          coeff_i: 0.05,
          noct: 45,
          longueur_mm: 2382,
          largeur_mm: 1134,
          epaisseur_mm: 30,
          surface_m2: 2.7,
          poids_kg: 33.5,
          nb_cellules: 144,
          format_cellules: "182x210mm",
          type: "bifacial_double_glass",
        },
        {
          nom: "Hi-MO 6 540W Explorer",
          puissance_max: 540,
          tension_mpp: 40.06,
          tension_vide: 47.48,
          courant_mpp: 13.48,
          courant_cc: 14.4,
          coeff_v: -0.23,
          coeff_p: -0.29,
          coeff_i: 0.05,
          noct: 45,
          longueur_mm: 2278,
          largeur_mm: 1134,
          epaisseur_mm: 35,
          surface_m2: 2.58,
          poids_kg: 27.5,
          nb_cellules: 144,
          format_cellules: "182x182mm",
          type: "monofacial",
        },
        {
          nom: "Hi-MO 5 415W",
          puissance_max: 415,
          tension_mpp: 31.25,
          tension_vide: 37.5,
          courant_mpp: 13.28,
          courant_cc: 14.13,
          coeff_v: -0.26,
          coeff_p: -0.34,
          coeff_i: 0.05,
          noct: 45,
          longueur_mm: 1722,
          largeur_mm: 1134,
          epaisseur_mm: 35,
          surface_m2: 1.95,
          poids_kg: 21.0,
          nb_cellules: 108,
          format_cellules: "182x182mm",
          type: "monofacial",
        },
      ],
    },
    canadian_solar: {
      nom_afic: "Canadian Solar",
      modeles: [
        {
          nom: "BiHiKu7 670W",
          puissance_max: 670,
          tension_mpp: 38.3,
          tension_vide: 45.5,
          courant_mpp: 17.5,
          courant_cc: 18.6,
          coeff_v: -0.26,
          coeff_p: -0.34,
          coeff_i: 0.05,
          noct: 41,
          longueur_mm: 2384,
          largeur_mm: 1303,
          epaisseur_mm: 33,
          surface_m2: 3.11,
          poids_kg: 37.8,
          nb_cellules: 132,
          format_cellules: "210x210mm",
          type: "bifacial_double_glass",
        },
        {
          nom: "TOPHiKu6 585W",
          puissance_max: 585,
          tension_mpp: 44.3,
          tension_vide: 52.2,
          courant_mpp: 13.21,
          courant_cc: 14.07,
          coeff_v: -0.26,
          coeff_p: -0.29,
          coeff_i: 0.05,
          noct: 41,
          longueur_mm: 2382,
          largeur_mm: 1134,
          epaisseur_mm: 30,
          surface_m2: 2.7,
          poids_kg: 32.0,
          nb_cellules: 144,
          format_cellules: "182x210mm",
          type: "bifacial_double_glass",
        },
        {
          nom: "HiKu6 455W",
          puissance_max: 455,
          tension_mpp: 34.4,
          tension_vide: 41.1,
          courant_mpp: 13.23,
          courant_cc: 14.05,
          coeff_v: -0.26,
          coeff_p: -0.34,
          coeff_i: 0.05,
          noct: 41,
          longueur_mm: 1909,
          largeur_mm: 1134,
          epaisseur_mm: 35,
          surface_m2: 2.16,
          poids_kg: 24.5,
          nb_cellules: 120,
          format_cellules: "182x182mm",
          type: "monofacial",
        },
      ],
    },
    ja_solar: {
      nom_afic: "JA Solar",
      modeles: [
        {
          nom: "JAM72S30 550W",
          puissance_max: 550,
          tension_mpp: 41.96,
          tension_vide: 49.9,
          courant_mpp: 13.11,
          courant_cc: 14.0,
          coeff_v: -0.27,
          coeff_p: -0.35,
          coeff_i: 0.045,
          noct: 45,
          longueur_mm: 2278,
          largeur_mm: 1134,
          epaisseur_mm: 35,
          surface_m2: 2.58,
          poids_kg: 28.8,
          nb_cellules: 144,
          format_cellules: "182x182mm",
          type: "monofacial",
        },
        {
          nom: "JAM54S31 405W",
          puissance_max: 405,
          tension_mpp: 31.21,
          tension_vide: 37.23,
          courant_mpp: 12.98,
          courant_cc: 13.87,
          coeff_v: -0.27,
          coeff_p: -0.35,
          coeff_i: 0.045,
          noct: 45,
          longueur_mm: 1722,
          largeur_mm: 1134,
          epaisseur_mm: 35,
          surface_m2: 1.95,
          poids_kg: 21.5,
          nb_cellules: 108,
          format_cellules: "182x182mm",
          type: "monofacial",
        },
      ],
    },
    tongwei_solar: {
      nom_afic: "Tongwei Solar",
      modeles: [
        {
          nom: "TH650W PM7",
          puissance_max: 650,
          tension_mpp: 37.9,
          tension_vide: 45.4,
          courant_mpp: 17.15,
          courant_cc: 18.25,
          coeff_v: -0.25,
          coeff_p: -0.3,
          coeff_i: 0.04,
          noct: 45,
          longueur_mm: 2384,
          largeur_mm: 1303,
          epaisseur_mm: 35,
          surface_m2: 3.11,
          poids_kg: 33.5,
          nb_cellules: 132,
          format_cellules: "210x210mm",
          type: "monofacial",
        },
      ],
    },
    astronergy: {
      nom_afic: "Astronergy",
      modeles: [
        {
          nom: "CHSM72 550W",
          puissance_max: 550,
          tension_mpp: 41.5,
          tension_vide: 49.9,
          courant_mpp: 13.25,
          courant_cc: 14.05,
          coeff_v: -0.27,
          coeff_p: -0.34,
          coeff_i: 0.04,
          noct: 44,
          longueur_mm: 2278,
          largeur_mm: 1134,
          epaisseur_mm: 35,
          surface_m2: 2.58,
          poids_kg: 28.5,
          nb_cellules: 144,
          format_cellules: "182x182mm",
          type: "monofacial",
        },
      ],
    },
    risen_energy: {
      nom_afic: "Risen Energy",
      modeles: [
        {
          nom: "Hyper-ion 700W",
          puissance_max: 700,
          tension_mpp: 41.8,
          tension_vide: 49.65,
          courant_mpp: 16.75,
          courant_cc: 17.68,
          coeff_v: -0.24,
          coeff_p: -0.26,
          coeff_i: 0.04,
          noct: 44,
          longueur_mm: 2384,
          largeur_mm: 1303,
          epaisseur_mm: 35,
          surface_m2: 3.11,
          poids_kg: 34.0,
          nb_cellules: 132,
          format_cellules: "210x210mm",
          type: "bifacial_double_glass",
        },
      ],
    },
    aiko_solar: {
      nom_afic: "AIKO Solar",
      modeles: [
        {
          nom: "Neostar 2S 465W",
          puissance_max: 465,
          tension_mpp: 35.61,
          tension_vide: 43.2,
          courant_mpp: 13.06,
          courant_cc: 13.95,
          coeff_v: -0.22,
          coeff_p: -0.26,
          coeff_i: 0.05,
          noct: 45,
          longueur_mm: 1909,
          largeur_mm: 1134,
          epaisseur_mm: 35,
          surface_m2: 2.16,
          poids_kg: 24.0,
          nb_cellules: 120,
          format_cellules: "182x182mm",
          type: "monofacial",
        },
        {
          nom: "Comet 2N 620W",
          puissance_max: 620,
          tension_mpp: 45.42,
          tension_vide: 54.33,
          courant_mpp: 13.65,
          courant_cc: 14.42,
          coeff_v: -0.22,
          coeff_p: -0.26,
          coeff_i: 0.05,
          noct: 45,
          longueur_mm: 2382,
          largeur_mm: 1134,
          epaisseur_mm: 30,
          surface_m2: 2.7,
          poids_kg: 32.0,
          nb_cellules: 144,
          format_cellules: "182x210mm",
          type: "bifacial_double_glass",
        },
      ],
    },
    dmegc_solar: {
      nom_afic: "DMEGC Solar",
      modeles: [
        {
          nom: "M10RT 500W",
          puissance_max: 500,
          tension_mpp: 38.2,
          tension_vide: 45.5,
          courant_mpp: 13.09,
          courant_cc: 13.9,
          coeff_v: -0.26,
          coeff_p: -0.3,
          coeff_i: 0.045,
          noct: 45,
          longueur_mm: 2094,
          largeur_mm: 1134,
          epaisseur_mm: 35,
          surface_m2: 2.37,
          poids_kg: 26.0,
          nb_cellules: 132,
          format_cellules: "182x182mm",
          type: "monofacial",
        },
      ],
    },
    qcells: {
      nom_afic: "Hanwha Q Cells",
      modeles: [
        {
          nom: "Q.TRON BLK 425W",
          puissance_max: 425,
          tension_mpp: 32.1,
          tension_vide: 38.5,
          courant_mpp: 13.24,
          courant_cc: 13.98,
          coeff_v: -0.27,
          coeff_p: -0.34,
          coeff_i: 0.04,
          noct: 43,
          longueur_mm: 1722,
          largeur_mm: 1134,
          epaisseur_mm: 32,
          surface_m2: 1.95,
          poids_kg: 21.5,
          nb_cellules: 108,
          format_cellules: "182x182mm",
          type: "monofacial_all_black",
        },
      ],
    },
    maxeon: {
      nom_afic: "Maxeon (SunPower)",
      modeles: [
        {
          nom: "Maxeon 6 440W",
          puissance_max: 440,
          tension_mpp: 43.6,
          tension_vide: 51.9,
          courant_mpp: 10.09,
          courant_cc: 10.75,
          coeff_v: -0.23,
          coeff_p: -0.29,
          coeff_i: 0.04,
          noct: 45,
          longueur_mm: 1690,
          largeur_mm: 1046,
          epaisseur_mm: 40,
          surface_m2: 1.77,
          poids_kg: 19.5,
          nb_cellules: 66,
          format_cellules: "IBC",
          type: "monofacial",
        },
      ],
    },
    huasun: {
      nom_afic: "Huasun",
      modeles: [
        {
          nom: "Everest G12R 720W",
          puissance_max: 720,
          tension_mpp: 43.83,
          tension_vide: 51.58,
          courant_mpp: 16.43,
          courant_cc: 17.25,
          coeff_v: -0.21,
          coeff_p: -0.26,
          coeff_i: 0.04,
          noct: 44,
          longueur_mm: 2384,
          largeur_mm: 1303,
          epaisseur_mm: 35,
          surface_m2: 3.11,
          poids_kg: 34.5,
          nb_cellules: 132,
          format_cellules: "210x210mm",
          type: "bifacial_double_glass",
        },
      ],
    },
    gcl_system: {
      nom_afic: "GCL System",
      modeles: [
        {
          nom: "GCL-M10 550W",
          puissance_max: 550,
          tension_mpp: 42.1,
          tension_vide: 49.9,
          courant_mpp: 13.07,
          courant_cc: 13.92,
          coeff_v: -0.27,
          coeff_p: -0.34,
          coeff_i: 0.04,
          noct: 45,
          longueur_mm: 2278,
          largeur_mm: 1134,
          epaisseur_mm: 35,
          surface_m2: 2.58,
          poids_kg: 28.5,
          nb_cellules: 144,
          format_cellules: "182x182mm",
          type: "monofacial",
        },
      ],
    },
    recom: {
      nom_afic: "RECOM",
      modeles: [
        {
          nom: "Black Tiger 700W",
          puissance_max: 700,
          tension_mpp: 45.42,
          tension_vide: 54.33,
          courant_mpp: 15.42,
          courant_cc: 16.35,
          coeff_v: -0.24,
          coeff_p: -0.26,
          coeff_i: 0.04,
          noct: 44,
          longueur_mm: 2384,
          largeur_mm: 1303,
          epaisseur_mm: 35,
          surface_m2: 3.11,
          poids_kg: 34.0,
          nb_cellules: 132,
          format_cellules: "210x210mm",
          type: "bifacial_double_glass",
        },
      ],
    },
    talesun: {
      nom_afic: "Talesun",
      modeles: [
        {
          nom: "Bistar 545W",
          puissance_max: 545,
          tension_mpp: 41.7,
          tension_vide: 49.7,
          courant_mpp: 13.07,
          courant_cc: 13.91,
          coeff_v: -0.27,
          coeff_p: -0.35,
          coeff_i: 0.04,
          noct: 45,
          longueur_mm: 2278,
          largeur_mm: 1134,
          epaisseur_mm: 35,
          surface_m2: 2.58,
          poids_kg: 28.0,
          nb_cellules: 144,
          format_cellules: "182x182mm",
          type: "monofacial",
        },
      ],
    },
    znshine_solar: {
      nom_afic: "ZNShine Solar",
      modeles: [
        {
          nom: "ZXM10 540W",
          puissance_max: 540,
          tension_mpp: 41.5,
          tension_vide: 49.5,
          courant_mpp: 13.02,
          courant_cc: 13.85,
          coeff_v: -0.27,
          coeff_p: -0.35,
          coeff_i: 0.04,
          noct: 45,
          longueur_mm: 2278,
          largeur_mm: 1134,
          epaisseur_mm: 35,
          surface_m2: 2.58,
          poids_kg: 28.0,
          nb_cellules: 144,
          format_cellules: "182x182mm",
          type: "monofacial",
        },
      ],
    },
    haitai_solar: {
      nom_afic: "Haitai Solar",
      modeles: [
        {
          nom: "Taiji 550W",
          puissance_max: 550,
          tension_mpp: 42.1,
          tension_vide: 49.9,
          courant_mpp: 13.07,
          courant_cc: 13.92,
          coeff_v: -0.27,
          coeff_p: -0.34,
          coeff_i: 0.04,
          noct: 45,
          longueur_mm: 2278,
          largeur_mm: 1134,
          epaisseur_mm: 35,
          surface_m2: 2.58,
          poids_kg: 28.5,
          nb_cellules: 144,
          format_cellules: "182x182mm",
          type: "monofacial",
        },
      ],
    },
    victron_energy: {
      nom_afic: "Victron Energy",
      modeles: [
        {
          nom: "BleuSolar 30W-12V",
          puissance_max: 30,
          tension_mpp: 18.0,
          tension_vide: 22.0,
          courant_mpp: 1.67,
          courant_cc: 1.83,
          coeff_v: -0.33,
          coeff_p: -0.45,
          coeff_i: 0.04,
          noct: 47,
          longueur_mm: 510,
          largeur_mm: 450,
          epaisseur_mm: 25,
          surface_m2: 0.23,
          poids_kg: 2.5,
          nb_cellules: 36,
          format_cellules: "125x125mm",
          type: "monofacial",
        },
        {
          nom: "BleuSolar 50W-12V",
          puissance_max: 50,
          tension_mpp: 18.0,
          tension_vide: 22.1,
          courant_mpp: 2.78,
          courant_cc: 3.05,
          coeff_v: -0.33,
          coeff_p: -0.45,
          coeff_i: 0.04,
          noct: 47,
          longueur_mm: 670,
          largeur_mm: 540,
          epaisseur_mm: 25,
          surface_m2: 0.36,
          poids_kg: 3.5,
          nb_cellules: 36,
          format_cellules: "125x125mm",
          type: "monofacial",
        },
        {
          nom: "Mono 115W-12V",
          puissance_max: 115,
          tension_mpp: 18.94,
          tension_vide: 23.23,
          courant_mpp: 6.08,
          courant_cc: 6.56,
          coeff_v: -0.33,
          coeff_p: -0.45,
          coeff_i: 0.04,
          noct: 47,
          longueur_mm: 1016,
          largeur_mm: 670,
          epaisseur_mm: 30,
          surface_m2: 0.68,
          poids_kg: 8.0,
          nb_cellules: 36,
          format_cellules: "156x156mm",
          type: "monofacial",
        },
        {
          nom: "Mono 175W-12V",
          puissance_max: 175,
          tension_mpp: 19.4,
          tension_vide: 23.7,
          courant_mpp: 9.03,
          courant_cc: 9.89,
          coeff_v: -0.33,
          coeff_p: -0.45,
          coeff_i: 0.04,
          noct: 47,
          longueur_mm: 1580,
          largeur_mm: 808,
          epaisseur_mm: 35,
          surface_m2: 1.28,
          poids_kg: 11.5,
          nb_cellules: 72,
          format_cellules: "156x156mm",
          type: "monofacial",
        },
        {
          nom: "Mono 305W-20V",
          puissance_max: 305,
          tension_mpp: 32.5,
          tension_vide: 39.7,
          courant_mpp: 9.38,
          courant_cc: 10.15,
          coeff_v: -0.29,
          coeff_p: -0.37,
          coeff_i: 0.04,
          noct: 45,
          longueur_mm: 1640,
          largeur_mm: 992,
          epaisseur_mm: 35,
          surface_m2: 1.63,
          poids_kg: 18.5,
          nb_cellules: 60,
          format_cellules: "156x156mm",
          type: "monofacial",
        },
      ],
    },
    ae_solar: {
      nom_afic: "AE Solar",
      modeles: [
        {
          nom: "Aurora 500W",
          puissance_max: 500,
          tension_mpp: 38.35,
          tension_vide: 46.59,
          courant_mpp: 13.04,
          courant_cc: 13.86,
          coeff_v: -0.27,
          coeff_p: -0.35,
          coeff_i: 0.048,
          noct: 45,
          longueur_mm: 2094,
          largeur_mm: 1134,
          epaisseur_mm: 35,
          surface_m2: 2.37,
          poids_kg: 26.5,
          nb_cellules: 132,
          format_cellules: "182x182mm",
          type: "monofacial",
        },
        {
          nom: "Hot-Spot Free 330W",
          puissance_max: 330,
          tension_mpp: 34.2,
          tension_vide: 41.6,
          courant_mpp: 9.65,
          courant_cc: 10.32,
          coeff_v: -0.33,
          coeff_p: -0.37,
          coeff_i: 0.06,
          noct: 45,
          longueur_mm: 1668,
          largeur_mm: 1002,
          epaisseur_mm: 35,
          surface_m2: 1.67,
          poids_kg: 18.5,
          nb_cellules: 60,
          format_cellules: "166x166mm",
          type: "monofacial",
        },
      ],
    },
    meyer_burger: {
      nom_afic: "Meyer Burger",
      modeles: [
        {
          nom: "Glass 380W",
          puissance_max: 380,
          tension_mpp: 38.1,
          tension_vide: 44.5,
          courant_mpp: 10.0,
          courant_cc: 10.7,
          coeff_v: -0.23,
          coeff_p: -0.26,
          coeff_i: 0.03,
          noct: 44,
          longueur_mm: 1767,
          largeur_mm: 1041,
          epaisseur_mm: 35,
          surface_m2: 1.84,
          poids_kg: 19.0,
          nb_cellules: 60,
          format_cellules: "166x166mm",
          type: "heterojunction",
        },
      ],
    },
    rec_solar: {
      nom_afic: "REC Solar",
      modeles: [
        {
          nom: "Alpha Pure-R 430W",
          puissance_max: 430,
          tension_mpp: 50.5,
          tension_vide: 59.7,
          courant_mpp: 8.52,
          courant_cc: 9.08,
          coeff_v: -0.24,
          coeff_p: -0.26,
          coeff_i: 0.04,
          noct: 44,
          longueur_mm: 1862,
          largeur_mm: 1044,
          epaisseur_mm: 30,
          surface_m2: 1.94,
          poids_kg: 21.5,
          nb_cellules: 80,
          format_cellules: "210x105mm",
          type: "heterojunction",
        },
      ],
    },
    suntech: {
      nom_afic: "Suntech",
      modeles: [
        {
          nom: "Ultra V 550W",
          puissance_max: 550,
          tension_mpp: 42.1,
          tension_vide: 50.0,
          courant_mpp: 13.07,
          courant_cc: 13.94,
          coeff_v: -0.27,
          coeff_p: -0.34,
          coeff_i: 0.04,
          noct: 45,
          longueur_mm: 2278,
          largeur_mm: 1134,
          epaisseur_mm: 35,
          surface_m2: 2.58,
          poids_kg: 28.5,
          nb_cellules: 144,
          format_cellules: "182x182mm",
          type: "monofacial",
        },
      ],
    },
    yingli_solar: {
      nom_afic: "Yingli Solar",
      modeles: [
        {
          nom: "Panda 3.0 570W",
          puissance_max: 570,
          tension_mpp: 42.5,
          tension_vide: 50.9,
          courant_mpp: 13.42,
          courant_cc: 14.21,
          coeff_v: -0.25,
          coeff_p: -0.3,
          coeff_i: 0.04,
          noct: 45,
          longueur_mm: 2278,
          largeur_mm: 1134,
          epaisseur_mm: 35,
          surface_m2: 2.58,
          poids_kg: 29.0,
          nb_cellules: 144,
          format_cellules: "182x182mm",
          type: "bifacial_double_glass",
        },
      ],
    },
    phono_solar: {
      nom_afic: "Phono Solar",
      modeles: [
        {
          nom: "Draco 580W",
          puissance_max: 580,
          tension_mpp: 43.1,
          tension_vide: 51.4,
          courant_mpp: 13.46,
          courant_cc: 14.19,
          coeff_v: -0.25,
          coeff_p: -0.29,
          coeff_i: 0.04,
          noct: 45,
          longueur_mm: 2278,
          largeur_mm: 1134,
          epaisseur_mm: 35,
          surface_m2: 2.58,
          poids_kg: 29.0,
          nb_cellules: 144,
          format_cellules: "182x182mm",
          type: "monofacial",
        },
      ],
    },
    seraphim: {
      nom_afic: "Seraphim",
      modeles: [
        {
          nom: "SIV 550W",
          puissance_max: 550,
          tension_mpp: 42.1,
          tension_vide: 49.9,
          courant_mpp: 13.07,
          courant_cc: 13.92,
          coeff_v: -0.27,
          coeff_p: -0.34,
          coeff_i: 0.04,
          noct: 45,
          longueur_mm: 2278,
          largeur_mm: 1134,
          epaisseur_mm: 35,
          surface_m2: 2.58,
          poids_kg: 28.5,
          nb_cellules: 144,
          format_cellules: "182x182mm",
          type: "monofacial",
        },
      ],
    },
    dah_solar: {
      nom_afic: "DAH Solar",
      modeles: [
        {
          nom: "Full-Screen 550W",
          puissance_max: 550,
          tension_mpp: 42.1,
          tension_vide: 50.0,
          courant_mpp: 13.07,
          courant_cc: 14.02,
          coeff_v: -0.27,
          coeff_p: -0.35,
          coeff_i: 0.04,
          noct: 45,
          longueur_mm: 2278,
          largeur_mm: 1134,
          epaisseur_mm: 35,
          surface_m2: 2.58,
          poids_kg: 28.5,
          nb_cellules: 144,
          format_cellules: "182x182mm",
          type: "monofacial",
        },
      ],
    },
    luxen_solar: {
      nom_afic: "Luxen Solar",
      modeles: [
        {
          nom: "Series 5 540W",
          puissance_max: 540,
          tension_mpp: 41.6,
          tension_vide: 49.6,
          courant_mpp: 12.99,
          courant_cc: 13.88,
          coeff_v: -0.27,
          coeff_p: -0.35,
          coeff_i: 0.04,
          noct: 45,
          longueur_mm: 2278,
          largeur_mm: 1134,
          epaisseur_mm: 35,
          surface_m2: 2.58,
          poids_kg: 28.0,
          nb_cellules: 144,
          format_cellules: "182x182mm",
          type: "monofacial",
        },
      ],
    },
    sharp: {
      nom_afic: "Sharp",
      modeles: [
        {
          nom: "NU-JC410 410W",
          puissance_max: 410,
          tension_mpp: 31.42,
          tension_vide: 37.6,
          courant_mpp: 13.05,
          courant_cc: 13.81,
          coeff_v: -0.26,
          coeff_p: -0.34,
          coeff_i: 0.04,
          noct: 44,
          longueur_mm: 1722,
          largeur_mm: 1134,
          epaisseur_mm: 35,
          surface_m2: 1.95,
          poids_kg: 21.5,
          nb_cellules: 108,
          format_cellules: "182x182mm",
          type: "monofacial",
        },
      ],
    },
    vikram_solar: {
      nom_afic: "Vikram Solar",
      modeles: [
        {
          nom: "Preva 545W",
          puissance_max: 545,
          tension_mpp: 41.8,
          tension_vide: 49.8,
          courant_mpp: 13.05,
          courant_cc: 13.91,
          coeff_v: -0.27,
          coeff_p: -0.35,
          coeff_i: 0.04,
          noct: 45,
          longueur_mm: 2278,
          largeur_mm: 1134,
          epaisseur_mm: 35,
          surface_m2: 2.58,
          poids_kg: 28.5,
          nb_cellules: 144,
          format_cellules: "182x182mm",
          type: "monofacial",
        },
      ],
    },
    sunnypower: {
      nom_afic: "Sunny Power",
      modeles: [
        {
          nom: "Poly 100W",
          puissance_max: 100,
          tension_mpp: 18.1,
          tension_vide: 22.1,
          courant_mpp: 5.53,
          courant_cc: 5.92,
          coeff_v: -0.33,
          coeff_p: -0.42,
          coeff_i: 0.05,
          noct: 45,
          longueur_mm: 1020,
          largeur_mm: 670,
          epaisseur_mm: 30,
          surface_m2: 0.68,
          poids_kg: 7.5,
          nb_cellules: 36,
          format_cellules: "156x156mm",
          type: "polycristallin",
        },
        {
          nom: "Poly 200W",
          puissance_max: 200,
          tension_mpp: 18.2,
          tension_vide: 22.2,
          courant_mpp: 10.99,
          courant_cc: 11.8,
          coeff_v: -0.33,
          coeff_p: -0.42,
          coeff_i: 0.05,
          noct: 45,
          longueur_mm: 1482,
          largeur_mm: 992,
          epaisseur_mm: 35,
          surface_m2: 1.47,
          poids_kg: 15.0,
          nb_cellules: 72,
          format_cellules: "156x156mm",
          type: "polycristallin",
        },
      ],
    },
    voltec_solar: {
      nom_afic: "Voltec Solar",
      modeles: [
        {
          nom: "Tarentula 375W",
          puissance_max: 375,
          tension_mpp: 34.5,
          tension_vide: 41.6,
          courant_mpp: 10.87,
          courant_cc: 11.45,
          coeff_v: -0.28,
          coeff_p: -0.34,
          coeff_i: 0.04,
          noct: 44,
          longueur_mm: 1765,
          largeur_mm: 1048,
          epaisseur_mm: 35,
          surface_m2: 1.85,
          poids_kg: 20.5,
          nb_cellules: 72,
          format_cellules: "166x166mm",
          type: "monofacial",
        },
      ],
    },
    dualsun: {
      nom_afic: "DualSun",
      modeles: [
        {
          nom: "Flash 425W TOPCon",
          puissance_max: 425,
          tension_mpp: 32.0,
          tension_vide: 38.5,
          courant_mpp: 13.28,
          courant_cc: 14.01,
          coeff_v: -0.25,
          coeff_p: -0.29,
          coeff_i: 0.045,
          noct: 45,
          longueur_mm: 1722,
          largeur_mm: 1134,
          epaisseur_mm: 35,
          surface_m2: 1.95,
          poids_kg: 22.0,
          nb_cellules: 108,
          format_cellules: "182x182mm",
          type: "monofacial",
        },
      ],
    },
    futurasun: {
      nom_afic: "FuturaSun",
      modeles: [
        {
          nom: "Silk Nova 430W",
          puissance_max: 430,
          tension_mpp: 32.4,
          tension_vide: 38.8,
          courant_mpp: 13.28,
          courant_cc: 14.05,
          coeff_v: -0.26,
          coeff_p: -0.31,
          coeff_i: 0.04,
          noct: 45,
          longueur_mm: 1722,
          largeur_mm: 1134,
          epaisseur_mm: 35,
          surface_m2: 1.95,
          poids_kg: 21.5,
          nb_cellules: 108,
          format_cellules: "182x182mm",
          type: "monofacial",
        },
      ],
    },
    axitec: {
      nom_afic: "Axitec",
      modeles: [
        {
          nom: "AXIpremium 410W",
          puissance_max: 410,
          tension_mpp: 31.4,
          tension_vide: 37.6,
          courant_mpp: 13.06,
          courant_cc: 13.88,
          coeff_v: -0.26,
          coeff_p: -0.34,
          coeff_i: 0.04,
          noct: 45,
          longueur_mm: 1722,
          largeur_mm: 1134,
          epaisseur_mm: 35,
          surface_m2: 1.95,
          poids_kg: 21.5,
          nb_cellules: 108,
          format_cellules: "182x182mm",
          type: "monofacial",
        },
      ],
    },
  },
};
